# Introduction to Python - Day 3 - Exercises

## Exercise 1

#### Question 1
##### Create an array of 25 numbers between 1 and 100 (including 100) and save to `arr1` variable.
##### Pring the type and data type of `arr1`.

In [52]:
import numpy as np

arr1 = np.linspace(1,100, 25)
print(arr1.dtype)
print(type(arr1))
print(arr1)

float64
<class 'numpy.ndarray'>
[  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]


#### Question 2
##### Create an array of 20 numbers from 50 to 70 (excluding 70).
##### Use `arange` function and assign the output to `arr2` variable.

In [4]:
arr2 = np.arange(50,70)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


#### Question 3
##### Create an array of all even numbers between 30 and 60 (excluding 60).
##### Create an array of numbers between 0 and 100 including, with step size of 25.

In [8]:
arr_even = np.arange(30,60,2)
print(arr_even)
arr_25 = np.arange(0,101,25)
print(arr_25)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]
[  0  25  50  75 100]


#### Question 4
##### Create an array of 10 numbers between 0 and 20 (including 20) assign to `arr3` variable.
##### Use linspace function.
##### Find the max, min and sum of the array.

In [12]:
arr3 = np.linspace(0,20,10)
print(arr3)
print(np.amin(arr3))
print(np.amax(arr3))
print(np.sum(arr3))

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
0.0
20.0
100.0


#### Question 5
##### Create two arrays of size 4 with the numbers 4, 5, 6, 4 in `array1` and 7, 2, 12, 16 in `array2`.
##### Find the sum, product, difference and quotient of `array1` and `array2` and save as `array_sum`, `product`, `difference`, and `quotient` variables respectively.
##### Print the results.

In [14]:
array1 = np.array([4,5,6,4]) 
array2 = np.array([7,2,12,16])

array_sum = array1 + array2
array_product = array1 * array2
array_difference = array1 - array2
array_quotient = array1 / array2

print(array_sum, array_product,array_difference,array_quotient)

[11  7 18 20] [28 10 72 64] [ -3   3  -6 -12] [0.57142857 2.5        0.5        0.25      ]


#### Question 6
##### Compute the absolute value of each entry in the following array `[5, -8, -66, 4]` and assign it to `abs_values` variable. Print the result.
##### Print the length of the `abs_values` array.
##### Print the 3rd element of `abs_values`.

In [40]:
import numpy
arr5 = np.array([5,-8,-66,4])
abs_values = np.abs(arr5)
print(len(abs_values))
print(abs_values[2])

4
66


#### Question 7
##### Print all numbers greater than 25 in `abs_values` array.

In [44]:
print(abs_values[(25 < abs_values)])

[66]


#### Question 8
##### Create a matrix with 3 rows and assign to variable `mat1`.
- [4, 5, 6]
- [8, 3, 2]
- [6, 7, 3]

##### Find the shape of the matrix.

In [53]:
mat1 = np.array([
    [4, 5, 6],
    [8, 3, 2],
    [6, 7, 3]
])
print(mat1.shape)

(3, 3)


#### Question 9
##### Find the value in the 2nd row and 3rd column.
##### Print the 2nd and 3rd rows.
##### Print the 1st column and rows up to the 2nd row.
##### Print all columns starting with column 2.

In [54]:
print(mat1[1,2])
print(mat1[1:3,:])
print(mat1[:2,0])
print(mat1[:,1:3])


2
[[8 3 2]
 [6 7 3]]
[4 8]
[[5 6]
 [3 2]
 [7 3]]


## Exercise 2

#### Question 1
##### Import `pandas` as `pd` and `os` packages.
##### Set the working directory to data directory.
##### Print the working directory.

In [56]:
import pandas as pd
import os
# Set `main_dir` to the location of your `af-werx` folder (for Mac).
data_dir = '/Users/datasociety/Desktop/af-werx/data'
os.chdir(data_dir)
print(os.getcwd())


/Users/datasociety/Desktop/af-werx/data


#### Question 2
##### Create a pandas Series object from a list of groceries below. Assign it to `shopping_series` variable and print it.
- milk
- eggs
- peppers
- cheese
- tomatos

##### Print out only the values of the Series.

In [58]:
shopping_series = pd.Series(['milk','eggs','peppers','cheese','tomatos'])
print(shopping_series)

0       milk
1       eggs
2    peppers
3     cheese
4    tomatos
dtype: object


#### Question 3
##### Create a pandas Date Series object starting from January 1st 2019 and ending with January 1st 2020 separated by a month. Assign the Series to `monthly_series` variable.
##### Print the result.
##### Create a pandas Date Series object starting from January 1st 2019 and covering 12 periods separated by a month. Assign the Series to `monthly_series_by_period` variable.
##### Print the result.
##### Are the two Series equivalent?

In [60]:
monthly_series = pd.date_range(start = '20190101', end = '20200101', freq = 'M')
print(monthly_series)

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31'],
              dtype='datetime64[ns]', freq='M')


In [62]:
monthly_series_by_period = pd.date_range(start = '20190101', freq = 'M', periods = 12)
print(monthly_series_by_period)

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31'],
              dtype='datetime64[ns]', freq='M')


In [63]:
monthly_series_by_period == monthly_series

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

#### Question 4
##### Create a pandas Date Series object starting from January 1st 2019 and ending with January 3rd 2019 separated by an hour. Assign the Series to `hourly_series` variable. 
##### Print the result.

In [64]:
hourly_series = pd.date_range(start = '20190101', end = '20190103', freq = 'H')
print(hourly_series)

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 01:00:00',
               '2019-01-01 02:00:00', '2019-01-01 03:00:00',
               '2019-01-01 04:00:00', '2019-01-01 05:00:00',
               '2019-01-01 06:00:00', '2019-01-01 07:00:00',
               '2019-01-01 08:00:00', '2019-01-01 09:00:00',
               '2019-01-01 10:00:00', '2019-01-01 11:00:00',
               '2019-01-01 12:00:00', '2019-01-01 13:00:00',
               '2019-01-01 14:00:00', '2019-01-01 15:00:00',
               '2019-01-01 16:00:00', '2019-01-01 17:00:00',
               '2019-01-01 18:00:00', '2019-01-01 19:00:00',
               '2019-01-01 20:00:00', '2019-01-01 21:00:00',
               '2019-01-01 22:00:00', '2019-01-01 23:00:00',
               '2019-01-02 00:00:00', '2019-01-02 01:00:00',
               '2019-01-02 02:00:00', '2019-01-02 03:00:00',
               '2019-01-02 04:00:00', '2019-01-02 05:00:00',
               '2019-01-02 06:00:00', '2019-01-02 07:00:00',
               '2019-01-

#### Question 5
##### Take `numpy` array `abs_values` from Exercise 1 Question 6 and convert it into a pandas Series object. Assign it to variable `abs_series`.
##### Print the result.
##### Then print the results of the following operations:
- Get the shape of the Series
- Find the mean of the Series
- Find the median of the Series
- Find the standard deviation of the Series
- Get unique values in the Series
- Get the number of unique values in the Series
- Get counts of unique values in the Series
- Find the position of the minimum value in the Series
- Find the position of the maximum value in the Series
- Rank items in the Series in descending order
- Sort values in the Series
- Find sum of the Series
- Find cumulative sum of the Series

In [65]:
abs_series = pd.Series(abs_values)
print(abs_series)

0     5
1     8
2    66
3     4
dtype: int64


In [78]:
print('Get the shape of the Series')
print(abs_series.shape)
print('Find the mean of the Series')
print(abs_series.mean())
print('Find the median of the Series')
print(abs_series.median())
print('Find the standard deviation of the Series')
print(abs_series.std())
print('Get unique values in the Series')
print(abs_series.unique())
print('Get the number of unique values in the Series')
print(abs_series.nunique())
print('Get counts of unique values in the Series')
print(abs_series.value_counts())
print('Find the position of the minimum value in the Series')
print(abs_series.idxmin())
print('Find the position of the maximum value in the Series')
print(abs_series.idxmax())
print('Rank items in the Series in descending order')
print(abs_series.rank(ascending = False))
print('Sort values in the Series')
print(abs_series.sort_values())
print('Find sum of the Series')
print(abs_series.sum())
print('Find cumulative sum of the Series')
print(abs_series.cumsum())

Get the shape of the Series
(4,)
Find the mean of the Series
20.75
Find the median of the Series
6.5
Find the standard deviation of the Series
30.21451086260816
Get unique values in the Series
[ 5  8 66  4]
Get the number of unique values in the Series
4
Get counts of unique values in the Series
5     1
4     1
66    1
8     1
dtype: int64
Find the position of the minimum value in the Series
3
Find the position of the maximum value in the Series
2
Rank items in the Series in descending order
0    3.0
1    2.0
2    1.0
3    4.0
dtype: float64
Sort values in the Series
3     4
0     5
1     8
2    66
dtype: int64
Find sum of the Series
83
Find cumulative sum of the Series
0     5
1    13
2    79
3    83
dtype: int64


## Exercise 3

#### Question 1
##### Use your `shopping_series` from Exercise 2 Question 2.
##### Create a Series object called `prices` that contains the following values: [2.5, 3.99, 1.95, 5.99, 1.29].
##### Create a Series object called `num_items` that contains the following values: [1, 1, 2, 1, 3].
##### Combine the three Series objects described above into a single DataFrame called `shopping_cart` naming the columns like so:
- `item_name`
- `item_price`
- `item_quantity`

##### Print the first few entries (i.e. the `head` of the DataFrame).

In [84]:
num_items = pd.Series([1, 1, 2, 1, 3])
prices = pd.Series([2.5, 3.99, 1.95, 5.99, 1.29])
shopping_cart = pd.DataFrame({'item_name': shopping_series, 'item_price': prices,'item_quantity':num_items})
print(shopping_cart.head())


  item_name  item_price  item_quantity
0      milk        2.50              1
1      eggs        3.99              1
2   peppers        1.95              2
3    cheese        5.99              1
4   tomatos        1.29              3


#### Question 2
##### Check the following characteristics of the `shopping_cart` object:
- Type
- Shape
- Show columns of the DataFrame
- Show information of the DataFrame
- Describe the DataFrame

##### How many columns are described in the last output?
##### Why do you think that's the case?
##### What is the 75-th percentile of the column `item_price`?
##### What is the standard deviation of the column `item_quantity`?

In [158]:
print(type(shopping_cart))
print(shopping_cart.shape)
print(shopping_cart.columns)
print(shopping_cart.info())
print(shopping_cart.describe())
print('item_price and item_quantity, ' + 
      'numeric data types, ' + 
      '3.99000, ', "0.894427")


<class 'pandas.core.frame.DataFrame'>
(5, 2)
Index(['item_price', 'item_quantity'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, milk to tomatos
Data columns (total 2 columns):
item_price       5 non-null float64
item_quantity    5 non-null int64
dtypes: float64(1), int64(1)
memory usage: 280.0+ bytes
None
       item_price  item_quantity
count     5.00000       5.000000
mean      3.14400       1.600000
std       1.87704       0.894427
min       1.29000       1.000000
25%       1.95000       1.000000
50%       2.50000       1.000000
75%       3.99000       2.000000
max       5.99000       3.000000
item_price and item_quantity, numeric data types, 3.99000,  0.894427


##### How many columns are described in the last output? - 2 (i.e. `item_price` and `item_quantity`)
##### Why do you think that's the case? - Because `item_name` contains character strings, on which we cannot perform a numerical summary like on the other two columns.
##### What is the 75-th percentile of the column `item_price`? - 3.99000
##### What is the standard deviation of the column `item_quantity`? - 0.894427

#### Question 3
##### Perform the following on `shopping_cart` DataFrame:
- Extract column `item_price`
- Extract columns `item_name` and`item_quantity`
- Extract row 3 


In [98]:
print(shopping_cart['item_price'])
print(shopping_cart[['item_price','item_quantity']])
print(shopping_cart.iloc[2,:])

0    2.50
1    3.99
2    1.95
3    5.99
4    1.29
Name: item_price, dtype: float64
   item_price  item_quantity
0        2.50              1
1        3.99              1
2        1.95              2
3        5.99              1
4        1.29              3
item_name        peppers
item_price          1.95
item_quantity          2
Name: 2, dtype: object


#### Question 4
##### Set index of `shopping_cart` DataFrame to `item_name`. Print the updated DataFrame.
##### Print only the index of the `shopping_cart` DataFrame.
##### Look up the row of the `shopping_cart` by using index value 'eggs'.
##### Reset index of the `shopping_cart`. Print the updated DataFrame.

In [103]:
shopping_cart = shopping_cart.reset_index()
shopping_cart = shopping_cart.set_index('item_name')
print(shopping_cart)
print(shopping_cart.index)
print(shopping_cart.loc['eggs'])

           item_price  item_quantity
item_name                           
milk             2.50              1
eggs             3.99              1
peppers          1.95              2
cheese           5.99              1
tomatos          1.29              3
Index(['milk', 'eggs', 'peppers', 'cheese', 'tomatos'], dtype='object', name='item_name')
item_price       3.99
item_quantity    1.00
Name: eggs, dtype: float64


#### Question 5
##### Read in 'TB_data.csv' into a variable called `tb_data` using pandas.
##### Print the first 20 rows of the DataFrame.

In [159]:
print(os.getcwd())
tb_data = pd.read_csv('TB_data.csv')
tb_data.head(21)

/Users/datasociety/Desktop/af-werx/data


country iso2 iso3  iso_numeric  year measure unit age_group sex  \
0   Afghanistan   AF  AFG            4  2017     inc  num      0-14   a   
1   Afghanistan   AF  AFG            4  2017     inc  num      0-14   f   
2   Afghanistan   AF  AFG            4  2017     inc  num      0-14   m   
3   Afghanistan   AF  AFG            4  2017     inc  num       0-4   f   
4   Afghanistan   AF  AFG            4  2017     inc  num       0-4   m   
5   Afghanistan   AF  AFG            4  2017     inc  num     15-24   f   
6   Afghanistan   AF  AFG            4  2017     inc  num     15-24   m   
7   Afghanistan   AF  AFG            4  2017     inc  num    15plus   a   
8   Afghanistan   AF  AFG            4  2017     inc  num    15plus   f   
9   Afghanistan   AF  AFG            4  2017     inc  num    15plus   m   
10  Afghanistan   AF  AFG            4  2017     inc  num     25-34   f   
11  Afghanistan   AF  AFG            4  2017     inc  num     25-34   m   
12  Afghanistan   AF  AFG            4  2017     inc  num     35-44   f   
13  Afghanistan   AF  AFG            4  2017     inc  num     35-44   m   
14  Afghanistan   AF  AFG            4  2017     inc  num     45-54   f   
15  Afghanistan   AF  AFG            4  2017     inc  num     45-54   m   
16  Afghanistan   AF  AFG            4  2017     inc  num      5-14   f   
17  Afghanistan   AF  AFG            4  2017     inc  num      5-14   m   
18  Afghanistan   AF  AFG            4  2017     inc  num     55-64   f   
19  Afghanistan   AF  AFG            4  2017     inc  num     55-64   m   
20  Afghanistan   AF  AFG            4  2017     inc  num    65plus   f   

     best       lo       hi  
0    7400   6500.0   8400.0  
1    3500   3200.0   3900.0  
2    3900   3500.0   4300.0  
3    1800   1700.0   1900.0  
4    2200   2000.0   2300.0  
5    7100   6200.0   8000.0  
6    6000   5300.0   6700.0  
7   60000  38000.0  82000.0  
8   31000  23000.0  39000.0  
9   29000  22000.0  36000.0  
10   6300   5500.0   7000.0  
11   5900   5200.0   6600.0  
12   5400   4800.0   6000.0  
13   5200   4600.0   5700.0  
14   4600   4100.0   5000.0  
15   4100   3700.0   4500.0  
16   1800   1700.0   1900.0  
17   1700   1600.0   1800.0  
18   3900   3600.0   4300.0  
19   3700   3400.0   4100.0  
20   3400   3100.0   3800.0

#### Question 6
##### Perform the following actions on `tb_data` object:
- Check the type of the object
- Get the shape of the object and save it to 2 variables and print both:
    - `nrows`
    - `ncols`
- Get a random sample from the data, make the size of the sample be 25
- Get a random sample from the data, make the size of the sample be 0.5% of the total number of rows

In [111]:
print(type(tb_data))
nrows, ncols = tb_data.shape
print(nrows, ncols)
print(tb_data.sample(n = 25))
tb_data.sample(frac = .005)

<class 'pandas.core.frame.DataFrame'>
3848 12
                               country iso2 iso3  iso_numeric  year measure  \
3689                        Uzbekistan   UZ  UZB          860  2017     inc   
1529                          Honduras   HN  HND          340  2017     inc   
858                      Côte d'Ivoire   CI  CIV          384  2017     inc   
2353                             Nauru   NR  NRU          520  2017     inc   
290                            Belarus   BY  BLR          112  2017     inc   
1749                            Jordan   JO  JOR          400  2017     inc   
3079                          Slovenia   SI  SVN          705  2017     inc   
122                          Argentina   AR  ARG           32  2017     inc   
1931                           Liberia   LR  LBR          430  2017     inc   
3206                         Sri Lanka   LK  LKA          144  2017     inc   
346                            Bermuda   BM  BMU           60  2017     inc   
2525  

country iso2 iso3  iso_numeric  year measure unit  \
1502                    Guyana   GY  GUY          328  2017     inc  num   
584                   Cameroon   CM  CMR          120  2017     inc  num   
557                   Cambodia   KH  KHM          116  2017     inc  num   
474                   Bulgaria   BG  BGR          100  2017     inc  num   
1791                     Kenya   KE  KEN          404  2017     inc  num   
523                    Burundi   BI  BDI          108  2017     inc  num   
110                   Anguilla   AI  AIA          660  2017     inc  num   
469          Brunei Darussalam   BN  BRN           96  2017     inc  num   
1130                   Eritrea   ER  ERI          232  2017     inc  num   
2847        Russian Federation   RU  RUS          643  2017     inc  num   
2065                  Malaysia   MY  MYS          458  2017     inc  num   
1912                   Lesotho   LS  LSO          426  2017     inc  num   
262                 Bangladesh   BD  BGD           50  2017     inc  num   
2870                    Rwanda   RW  RWA          646  2017     inc  num   
294                    Belarus   BY  BLR          112  2017     inc  num   
643   Central African Republic   CF  CAF          140  2017     inc  num   
270                   Barbados   BB  BRB           52  2017     inc  num   
793                   Colombia   CO  COL          170  2017     inc  num   
3573                   Ukraine   UA  UKR          804  2017     inc  num   

     age_group sex    best        lo        hi  
1502       all   m     420     340.0     510.0  
584        0-4   m    1900    1800.0    2100.0  
557       0-14   m    3400    3100.0    3700.0  
474        0-4   f      41      39.0      42.0  
1791    15plus   m   95000   63000.0  127000.0  
523       0-14   m     830     740.0     910.0  
110        all   m       2       1.0       3.0  
469        all   f     100      94.0     110.0  
1130    15plus   f    1300     780.0    1800.0  
2847       all   m   60000   40000.0   79000.0  
2065     35-44   m    2900    2700.0    3000.0  
1912     55-64   m     720     660.0     780.0  
262        all   a  364000  257000.0  471000.0  
2870       all   a    7000    5200.0    8700.0  
294     65plus   f     230     220.0     250.0  
643        0-4   m     830     760.0     900.0  
270     15plus   m       0       NaN       NaN  
793     65plus   f    1100    1100.0    1200.0  
3573    65plus   f    1500    1400.0    1600.0

#### Question 7
##### Get to know your `tb_data` object by completing the following tasks:
- Show columns of the DataFrame
- Show data types of the columns of the DataFrame
- Show information about the DataFrame
- Describe the DataFrame

##### How many columns do you see in the description of this data?
##### Which columns have you meaningful statistical descriptions?
##### Why do you think this is the case?
##### Once you have completed these tasks, open the `TB_data_dictionary.csv` in your `data` folder and look up the names of the columns of your data under `variable_name` column and study the `code_list` and `definition` columns corresponding to the variables in your dataset.
##### Describe in a few short sentences what this dataset represents and what basic facts you have learned by looking at this data and describing the columns.

In [120]:
print(tb_data.columns)
print(tb_data.dtypes)
print(tb_data.info())
print(tb_data.describe())
print('5 columns ; best,low,and hi; the other columns are object types and therefore cannot be summarized')

Index(['country', 'iso2', 'iso3', 'iso_numeric', 'year', 'measure', 'unit',
       'age_group', 'sex', 'best', 'lo', 'hi'],
      dtype='object')
country         object
iso2            object
iso3            object
iso_numeric      int64
year             int64
measure         object
unit            object
age_group       object
sex             object
best             int64
lo             float64
hi             float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3848 entries, 0 to 3847
Data columns (total 12 columns):
country        3848 non-null object
iso2           3823 non-null object
iso3           3848 non-null object
iso_numeric    3848 non-null int64
year           3848 non-null int64
measure        3848 non-null object
unit           3848 non-null object
age_group      3848 non-null object
sex            3848 non-null object
best           3848 non-null int64
lo             3785 non-null float64
hi             3785 non-null float64
dtypes: float64(2), int64(

##### How many columns do you see in the description of this data? - 5 columns: `iso_numeric`, `year`, `best`, `lo`, `hi`
##### Which columns have you meaningful statistical descriptions? - columns `best`, `lo`, and `hi` have meaningful statistical summaries
##### Why do you think this is the case? - `iso_numeric` and `year` although numeric, cannot be summarized by the basic statistical metrics like mean or standard deviation, because `iso_numeric` is an identifying column, where numbers represent unique IDs of countries; `year` is a date column that serves as a filtering/sorting/grouping variable or a variable that will allow us detect temporal patterns, its statistical summary provides little value. Besides, we can see that we only have a single year (2017) in our data.


##### Sample description:

This dataset represents the estimates of tuberculosis incidents by age and sex for all countries in 2017. According to data dictionary and our quick glance at statistical summary it contains information about:
- The country (there are several identifying columns related to it)
- The year (2017)
- The age group 
- The sex
- The best estimates of tuberculosis incidents (with mean number being `0` and maximum `2740000`, for instance)
- The lower bound estimates, and
- The higher bound estimates

#### Question 8
##### Set the index of the `tb_data` to be equal to `iso3` column. Print the index of the `tb_data`.
##### Look up rows of the DataFrame by the index (use index values listed below):
- CAN
- USA
- AUS
- GBR
- ARG
- IND

##### Reset index. Print the first 10 rows of the DataFrame.

In [174]:
tb_data = tb_data.reset_index()
tb_data = tb_data.set_index('iso3')
print(tb_data.index)

Index(['AFG', 'AFG', 'AFG', 'AFG', 'AFG', 'AFG', 'AFG', 'AFG', 'AFG', 'AFG',
       ...
       'ZWE', 'ZWE', 'ZWE', 'ZWE', 'ZWE', 'ZWE', 'ZWE', 'ZWE', 'ZWE', 'ZWE'],
      dtype='object', name='iso3', length=3848)


In [175]:
print(tb_data.loc['USA'])

      index                   country iso2  iso_numeric  year measure unit  \
iso3                                                                         
USA    3637  United States of America   US          840  2017     inc  num   
USA    3638  United States of America   US          840  2017     inc  num   
USA    3639  United States of America   US          840  2017     inc  num   
USA    3640  United States of America   US          840  2017     inc  num   
USA    3641  United States of America   US          840  2017     inc  num   
USA    3642  United States of America   US          840  2017     inc  num   
USA    3643  United States of America   US          840  2017     inc  num   
USA    3644  United States of America   US          840  2017     inc  num   
USA    3645  United States of America   US          840  2017     inc  num   
USA    3646  United States of America   US          840  2017     inc  num   
USA    3647  United States of America   US          840  2017   

In [138]:
tb_data = tb_data.reset_index()

## Exercise 4

#### Question 1
##### Group `tb_data` by age and assign to variable `tb_data_grouped_by_age`.
##### Group `tb_data` by sex and assign to variable `tb_data_grouped_by_sex`.
##### Group `tb_data` by sex and age and assign to variable `tb_data_grouped`.
##### _Hint: when grouping by multiple columns use a list of columns as input!_
##### Print results of the first group for each.
##### Now, look up the following, by applying summary functions to `tb_data_grouped` DataFrame:
- The count for `country` column
- The median for `best` column
- The standard deviation for `hi` column

##### Assign the median for `best` column to a variable called `tb_data_median_by_age_sex`

In [190]:
tb_data_grouped_by_age = tb_data.groupby('age_group')

tb_data_grouped_by_sex = tb_data.groupby('sex')

tb_data_grouped = tb_data.groupby(['age_group','sex'])
print(tb_data_grouped_by_sex.first())
print(tb_data_grouped_by_age.first())
print(tb_data_grouped.first())

     index      country iso2  iso_numeric  year measure unit age_group  best  \
sex                                                                            
a        0  Afghanistan   AF            4  2017     inc  num      0-14  7400   
f        1  Afghanistan   AF            4  2017     inc  num      0-14  3500   
m        2  Afghanistan   AF            4  2017     inc  num      0-14  3900   

         lo      hi  
sex                  
a    6500.0  8400.0  
f    3200.0  3900.0  
m    3500.0  4300.0  
           index      country iso2  iso_numeric  year measure unit sex   best  \
age_group                                                                       
0-14           0  Afghanistan   AF            4  2017     inc  num   a   7400   
0-4            3  Afghanistan   AF            4  2017     inc  num   f   1800   
15-24          5  Afghanistan   AF            4  2017     inc  num   f   7100   
15plus         7  Afghanistan   AF            4  2017     inc  num   a  60000   
25-

In [193]:
print(tb_data_grouped.count()[['country']])
print(tb_data_grouped.std()[['hi']])
tb_data_median_by_age_sex = tb_data_grouped.median()[['best']]
print(tb_data_median_by_age_sex)

               country
age_group sex         
0-14      a        216
          f        216
          m        216
0-4       f        119
          m        119
15-24     f        119
          m        119
15plus    a        216
          f        216
          m        216
25-34     f        119
          m        119
35-44     f        119
          m        119
45-54     f        119
          m        119
5-14      f        119
          m        119
55-64     f        119
          m        119
65plus    f        119
          m        119
all       a        216
          f        216
          m        216
                          hi
age_group sex               
0-14      a     21085.864049
          f      9735.553655
          m     10769.675348
0-4       f      6160.933072
          m      7618.365367
15-24     f     23235.898010
          m     29207.245583
15plus    a    260164.433483
          f     80252.814743
          m    164376.274722
25-34     f     20719.662110
  

#### Question 2
##### Sort grouped median values of `best` estimates data you created above in descending order.
##### Which age-sex group has the highest tuberculosis incidents estimate?
##### Which age-sex group has the lowest tuberculosis incidents estimate?

In [196]:
print(tb_data_median_by_age_sex.sort_values(by = ['best'], ascending = [False]))

print('15plus')
print('0-14')

                 best
age_group sex        
all       a    2750.0
15plus    a    2450.0
all       m    1650.0
15plus    m    1500.0
25-34     m    1500.0
35-44     m    1400.0
15-24     m    1200.0
45-54     m    1100.0
all       f    1000.0
25-34     f    1000.0
55-64     m     950.0
65plus    m     930.0
15plus    f     865.0
15-24     f     850.0
35-44     f     760.0
65plus    f     650.0
45-54     f     590.0
55-64     f     540.0
0-4       m     460.0
5-14      f     410.0
          m     400.0
0-4       f     380.0
0-14      a     295.0
          m     155.0
          f     140.0
15plus
0-14


##### All ages and all sexes have the highest incidents estimates, which is understandable, because all age and sex groups are included here.
##### 0-14-year old females have the lowest incidents estimates.

#### Question 3
##### Use `tb_data_grouped_by_age` data.
##### Compute the mean of the `best` column and assign to `tb_data_grouped_mean` variable.
##### Print the result.
##### Filter the rows of`tb_data_grouped_mean` variable so that only age groups with instances of tuberculosis between 7000 and 10000 are displayed (including 5000, but excluding 10000).
##### Which age groups did you get?

In [203]:
tb_data_grouped_mean = tb_data_grouped_by_age.mean()[['best']]
print(tb_data_grouped_mean)
print(tb_data_grouped_mean.query('7000 <= best < 10000'))
print('25-34','35-44')

                   best
age_group              
0-14        3107.552469
0-4         2208.109244
15-24       6555.189076
15plus     27915.486111
25-34       7638.306723
35-44       7135.184874
45-54       6337.655462
5-14        2010.546218
55-64       5156.243697
65plus      5073.268908
all        31005.768519
                  best
age_group             
25-34      7638.306723
35-44      7135.184874
25-34 35-44


#### Question 4
##### Use `tb_data_grouped_mean` data.
##### Filter the `best` column of`tb_data_grouped_mean` variable so that only age groups with instances of tuberculosis above 5000 are displayed. Save as a series to `above_5000` variable.
##### Print the result.
##### Append the above series to `tb_data_grouped_mean` DataFrame by adding it as a column with the same name.
##### Print the result.


In [212]:
above_5000 = tb_data_grouped_mean['best'] > 5000
print(above_5000)
tb_data_grouped_mean['above_5000'] = above_5000
print(tb_data_grouped_mean)
del tb_data_grouped_mean['above_5000']
print(tb_data_grouped_mean)

age_group
0-14      False
0-4       False
15-24      True
15plus     True
25-34      True
35-44      True
45-54      True
5-14      False
55-64      True
65plus     True
all        True
Name: best, dtype: bool
                   best  above_5000
age_group                          
0-14        3107.552469       False
0-4         2208.109244       False
15-24       6555.189076        True
15plus     27915.486111        True
25-34       7638.306723        True
35-44       7135.184874        True
45-54       6337.655462        True
5-14        2010.546218       False
55-64       5156.243697        True
65plus      5073.268908        True
all        31005.768519        True
                   best
age_group              
0-14        3107.552469
0-4         2208.109244
15-24       6555.189076
15plus     27915.486111
25-34       7638.306723
35-44       7135.184874
45-54       6337.655462
5-14        2010.546218
55-64       5156.243697
65plus      5073.268908
all        31005.768519
